import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about/About";
import Hero from "../components/hero/Hero";
import ProjectCard from "../components/projects/ProjectCard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero />
      <About />
      {/* <ProjectCard /> */}
    </div>
  );
};

export default Home;
