import type { NextPage } from "next";
import Head from "next/head";
import About from "../components/about/About";
import ContactFooter from "../components/footer/ContactFooter";
import Hero from "../components/hero/Hero";
import Learning from "../components/learning/Learning";
import ProjectCard from "../components/projects/ProjectCard";
import Techstack from "../components/techstack/Techstack";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Hero />
      <About />
      <Learning />
      <Techstack />
    </div>
  );
};

export default Home;
